### ISSUE TITLE
Invalid SMTP Credentials ?

### ISSUE THREAD

**Issue by Docusland** [vv221/la-bouee-corsaire#5]
Currently we do not receive emails from the application when we create a user account. 
Could you please fix this ? 

Thanks,
Erwann

**Comment by vv221** [comment]
Sadly I do not have access to the configuration of the mail server for the current instance of the application, so I won’t be able to do anything but to provide basic advice:
_check the credentials in app/config/parameter.yml, then double-check them
_write a very basic mail sending PHP script using the same credentials to test them outside of the application
_try using another mail server, I can create a temporary account on my own server for testing purposes if you’d like me to

**Comment by ErwannFace** [comment]
Solved by fixing the parameters and config yml files. 
For information, I had to set transport and port settings for OVH, as well as cleaning the cache folder.
In parameters, I added :
    mailer_transport: mail
    mailer_auth_mode: login
    mailer_host: SSL0.OVH.NET
    mailer_port: 587

Thanks,
