### ISSUE TITLE
Impossible to remove a "need"

### ISSUE THREAD

**Issue by ErwannFace** [vv221/la-bouee-corsaire#6]
As an administrator I managed to create a "Need". 
Even though I should not have done this, I wonder how we remove a "Need". Could it be possible (as I am the owner of the Need) to have a button or dropdown list for setting the status of the need to "removed"?

Thanks,

**Comment by vv221** [comment]
You can already disable a task by using the URL /disable/{task_id}

I will integrate a link to this URL from the task edition form as soon as I have a bit of free time.

**Comment by vv221** [comment]
Commit [url=https://github.com/vv221/la-bouee-corsaire/commit/b6f463cf38b4c075a25b4dd323c15bf9c0e772c5]b6f463c[/url] add a disabling link to the task edition form.
